server:
  port: 8888

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/common-db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: john13767522399@

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*